version: '3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_PASSWORD: wordpress-password
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress-test
      WORDPRESS_DB_NAME: wordpress-test
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - wp_data:/var/www/html/wp-content
    depends_on:
      - db
      - wp-cli
    restart: always
    links:
      - db

  db:
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root-password

  wp-cli:
    image: wordpress:cli
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db
    restart: always

volumes:
  db_data:
  wp_data:
